export const areaCodeMapping: {
  [key: string]: { stateName: string; stateCode: string };
} = {
  '201': { stateName: 'NJ', stateCode: 'NJ' },
  '202': { stateName: 'DC', stateCode: 'DC' },
  '203': { stateName: 'CT', stateCode: 'CT' },
  '204': { stateName: 'MANITOBA', stateCode: 'MANITOBA' },
  '205': { stateName: 'AL', stateCode: 'AL' },
  '206': { stateName: 'WA', stateCode: 'WA' },
  '207': { stateName: 'ME', stateCode: 'ME' },
  '208': { stateName: 'ID', stateCode: 'ID' },
  '209': { stateName: 'CA', stateCode: 'CA' },
  '210': { stateName: 'TX', stateCode: 'TX' },
  '212': { stateName: 'NY', stateCode: 'NY' },
  '213': { stateName: 'CA', stateCode: 'CA' },
  '214': { stateName: 'TX', stateCode: 'TX' },
  '215': { stateName: 'PA', stateCode: 'PA' },
  '216': { stateName: 'OH', stateCode: 'OH' },
  '217': { stateName: 'IL', stateCode: 'IL' },
  '218': { stateName: 'MN', stateCode: 'MN' },
  '219': { stateName: 'IN', stateCode: 'IN' },
  '220': { stateName: 'OH', stateCode: 'OH' },
  '223': { stateName: 'PA', stateCode: 'PA' },
  '224': { stateName: 'IL', stateCode: 'IL' },
  '225': { stateName: 'LA', stateCode: 'LA' },
  '226': { stateName: 'ONTARIO', stateCode: 'ONTARIO' },
  '227': { stateName: 'MD', stateCode: 'MD' },
  '228': { stateName: 'MS', stateCode: 'MS' },
  '229': { stateName: 'GA', stateCode: 'GA' },
  '231': { stateName: 'MI', stateCode: 'MI' },
  '234': { stateName: 'OH', stateCode: 'OH' },
  '235': { stateName: 'MO', stateCode: 'MO' },
  '236': { stateName: 'BRITISH COLUMBIA', stateCode: 'BRITISH COLUMBIA' },
  '239': { stateName: 'FL', stateCode: 'FL' },
  '240': { stateName: 'MD', stateCode: 'MD' },
  '242': { stateName: 'BAHAMAS', stateCode: 'BAHAMAS' },
  '246': { stateName: 'BARBADOS', stateCode: 'BARBADOS' },
  '248': { stateName: 'MI', stateCode: 'MI' },
  '249': { stateName: 'ONTARIO', stateCode: 'ONTARIO' },
  '250': { stateName: 'BRITISH COLUMBIA', stateCode: 'BRITISH COLUMBIA' },
  '251': { stateName: 'AL', stateCode: 'AL' },
  '252': { stateName: 'NC', stateCode: 'NC' },
  '253': { stateName: 'WA', stateCode: 'WA' },
  '254': { stateName: 'TX', stateCode: 'TX' },
  '256': { stateName: 'AL', stateCode: 'AL' },
  '260': { stateName: 'IN', stateCode: 'IN' },
  '262': { stateName: 'WI', stateCode: 'WI' },
  '263': { stateName: 'QUEBEC', stateCode: 'QUEBEC' },
  '264': { stateName: 'ANGUILLA', stateCode: 'ANGUILLA' },
  '267': { stateName: 'PA', stateCode: 'PA' },
  '268': { stateName: 'ANTIGUA/BARBUDA', stateCode: 'ANTIGUA/BARBUDA' },
  '269': { stateName: 'MI', stateCode: 'MI' },
  '270': { stateName: 'KY', stateCode: 'KY' },
  '272': { stateName: 'PA', stateCode: 'PA' },
  '274': { stateName: 'WI', stateCode: 'WI' },
  '276': { stateName: 'VA', stateCode: 'VA' },
  '279': { stateName: 'CA', stateCode: 'CA' },
  '281': { stateName: 'TX', stateCode: 'TX' },
  '283': { stateName: 'OH', stateCode: 'OH' },
  '284': {
    stateName: 'BRITISH VIRGIN ISLANDS',
    stateCode: 'BRITISH VIRGIN ISLANDS',
  },
  '289': { stateName: 'ONTARIO', stateCode: 'ONTARIO' },
  '301': { stateName: 'MD', stateCode: 'MD' },
  '302': { stateName: 'DE', stateCode: 'DE' },
  '303': { stateName: 'CO', stateCode: 'CO' },
  '304': { stateName: 'WV', stateCode: 'WV' },
  '305': { stateName: 'FL', stateCode: 'FL' },
  '306': { stateName: 'SASKATCHEWAN', stateCode: 'SASKATCHEWAN' },
  '307': { stateName: 'WY', stateCode: 'WY' },
  '308': { stateName: 'NE', stateCode: 'NE' },
  '309': { stateName: 'IL', stateCode: 'IL' },
  '310': { stateName: 'CA', stateCode: 'CA' },
  '312': { stateName: 'IL', stateCode: 'IL' },
  '313': { stateName: 'MI', stateCode: 'MI' },
  '314': { stateName: 'MO', stateCode: 'MO' },
  '315': { stateName: 'NY', stateCode: 'NY' },
  '316': { stateName: 'KS', stateCode: 'KS' },
  '317': { stateName: 'IN', stateCode: 'IN' },
  '318': { stateName: 'LA', stateCode: 'LA' },
  '319': { stateName: 'IA', stateCode: 'IA' },
  '320': { stateName: 'MN', stateCode: 'MN' },
  '321': { stateName: 'FL', stateCode: 'FL' },
  '323': { stateName: 'CA', stateCode: 'CA' },
  '324': { stateName: 'FL', stateCode: 'FL' },
  '325': { stateName: 'TX', stateCode: 'TX' },
  '326': { stateName: 'OH', stateCode: 'OH' },
  '327': { stateName: 'AR', stateCode: 'AR' },
  '329': { stateName: 'NY', stateCode: 'NY' },
  '330': { stateName: 'OH', stateCode: 'OH' },
  '331': { stateName: 'IL', stateCode: 'IL' },
  '332': { stateName: 'NY', stateCode: 'NY' },
  '334': { stateName: 'AL', stateCode: 'AL' },
  '336': { stateName: 'NC', stateCode: 'NC' },
  '337': { stateName: 'LA', stateCode: 'LA' },
  '339': { stateName: 'MA', stateCode: 'MA' },
  '340': { stateName: 'VI', stateCode: 'VI' },
  '341': { stateName: 'CA', stateCode: 'CA' },
  '343': { stateName: 'ONTARIO', stateCode: 'ONTARIO' },
  '345': { stateName: 'CAYMAN ISLANDS', stateCode: 'CAYMAN ISLANDS' },
  '346': { stateName: 'TX', stateCode: 'TX' },
  '347': { stateName: 'NY', stateCode: 'NY' },
  '350': { stateName: 'CA', stateCode: 'CA' },
  '351': { stateName: 'MA', stateCode: 'MA' },
  '352': { stateName: 'FL', stateCode: 'FL' },
  '353': { stateName: 'WI', stateCode: 'WI' },
  '354': { stateName: 'QUEBEC', stateCode: 'QUEBEC' },
  '360': { stateName: 'WA', stateCode: 'WA' },
  '361': { stateName: 'TX', stateCode: 'TX' },
  '363': { stateName: 'NY', stateCode: 'NY' },
  '364': { stateName: 'KY', stateCode: 'KY' },
  '365': { stateName: 'ONTARIO', stateCode: 'ONTARIO' },
  '367': { stateName: 'QUEBEC', stateCode: 'QUEBEC' },
  '368': { stateName: 'ALBERTA', stateCode: 'ALBERTA' },
  '369': { stateName: 'CA', stateCode: 'CA' },
  '380': { stateName: 'OH', stateCode: 'OH' },
  '382': { stateName: 'ONTARIO', stateCode: 'ONTARIO' },
  '385': { stateName: 'UT', stateCode: 'UT' },
  '386': { stateName: 'FL', stateCode: 'FL' },
  '401': { stateName: 'RI', stateCode: 'RI' },
  '402': { stateName: 'NE', stateCode: 'NE' },
  '403': { stateName: 'ALBERTA', stateCode: 'ALBERTA' },
  '404': { stateName: 'GA', stateCode: 'GA' },
  '405': { stateName: 'OK', stateCode: 'OK' },
  '406': { stateName: 'MT', stateCode: 'MT' },
  '407': { stateName: 'FL', stateCode: 'FL' },
  '408': { stateName: 'CA', stateCode: 'CA' },
  '409': { stateName: 'TX', stateCode: 'TX' },
  '410': { stateName: 'MD', stateCode: 'MD' },
  '412': { stateName: 'PA', stateCode: 'PA' },
  '413': { stateName: 'MA', stateCode: 'MA' },
  '414': { stateName: 'WI', stateCode: 'WI' },
  '415': { stateName: 'CA', stateCode: 'CA' },
  '416': { stateName: 'ONTARIO', stateCode: 'ONTARIO' },
  '417': { stateName: 'MO', stateCode: 'MO' },
  '418': { stateName: 'QUEBEC', stateCode: 'QUEBEC' },
  '419': { stateName: 'OH', stateCode: 'OH' },
  '423': { stateName: 'TN', stateCode: 'TN' },
  '424': { stateName: 'CA', stateCode: 'CA' },
  '425': { stateName: 'WA', stateCode: 'WA' },
  '428': { stateName: 'NEW BRUNSWICK', stateCode: 'NEW BRUNSWICK' },
  '430': { stateName: 'TX', stateCode: 'TX' },
  '431': { stateName: 'MANITOBA', stateCode: 'MANITOBA' },
  '432': { stateName: 'TX', stateCode: 'TX' },
  '434': { stateName: 'VA', stateCode: 'VA' },
  '435': { stateName: 'UT', stateCode: 'UT' },
  '436': { stateName: 'OH', stateCode: 'OH' },
  '437': { stateName: 'ONTARIO', stateCode: 'ONTARIO' },
  '438': { stateName: 'QUEBEC', stateCode: 'QUEBEC' },
  '440': { stateName: 'OH', stateCode: 'OH' },
  '441': { stateName: 'BERMUDA', stateCode: 'BERMUDA' },
  '442': { stateName: 'CA', stateCode: 'CA' },
  '443': { stateName: 'MD', stateCode: 'MD' },
  '445': { stateName: 'PA', stateCode: 'PA' },
  '447': { stateName: 'IL', stateCode: 'IL' },
  '448': { stateName: 'FL', stateCode: 'FL' },
  '450': { stateName: 'QUEBEC', stateCode: 'QUEBEC' },
  '458': { stateName: 'OR', stateCode: 'OR' },
  '463': { stateName: 'IN', stateCode: 'IN' },
  '464': { stateName: 'IL', stateCode: 'IL' },
  '468': { stateName: 'QUEBEC', stateCode: 'QUEBEC' },
  '469': { stateName: 'TX', stateCode: 'TX' },
  '470': { stateName: 'GA', stateCode: 'GA' },
  '472': { stateName: 'NC', stateCode: 'NC' },
  '473': { stateName: 'GRENADA', stateCode: 'GRENADA' },
  '474': { stateName: 'SASKATCHEWAN', stateCode: 'SASKATCHEWAN' },
  '475': { stateName: 'CT', stateCode: 'CT' },
  '478': { stateName: 'GA', stateCode: 'GA' },
  '479': { stateName: 'AR', stateCode: 'AR' },
  '480': { stateName: 'AZ', stateCode: 'AZ' },
  '484': { stateName: 'PA', stateCode: 'PA' },
  '501': { stateName: 'AR', stateCode: 'AR' },
  '502': { stateName: 'KY', stateCode: 'KY' },
  '503': { stateName: 'OR', stateCode: 'OR' },
  '504': { stateName: 'LA', stateCode: 'LA' },
  '505': { stateName: 'NM', stateCode: 'NM' },
  '506': { stateName: 'NEW BRUNSWICK', stateCode: 'NEW BRUNSWICK' },
  '507': { stateName: 'MN', stateCode: 'MN' },
  '508': { stateName: 'MA', stateCode: 'MA' },
  '509': { stateName: 'WA', stateCode: 'WA' },
  '510': { stateName: 'CA', stateCode: 'CA' },
  '512': { stateName: 'TX', stateCode: 'TX' },
  '513': { stateName: 'OH', stateCode: 'OH' },
  '514': { stateName: 'QUEBEC', stateCode: 'QUEBEC' },
  '515': { stateName: 'IA', stateCode: 'IA' },
  '516': { stateName: 'NY', stateCode: 'NY' },
  '517': { stateName: 'MI', stateCode: 'MI' },
  '518': { stateName: 'NY', stateCode: 'NY' },
  '519': { stateName: 'ONTARIO', stateCode: 'ONTARIO' },
  '520': { stateName: 'AZ', stateCode: 'AZ' },
  '530': { stateName: 'CA', stateCode: 'CA' },
  '531': { stateName: 'NE', stateCode: 'NE' },
  '534': { stateName: 'WI', stateCode: 'WI' },
  '539': { stateName: 'OK', stateCode: 'OK' },
  '540': { stateName: 'VA', stateCode: 'VA' },
  '541': { stateName: 'OR', stateCode: 'OR' },
  '548': { stateName: 'ONTARIO', stateCode: 'ONTARIO' },
  '551': { stateName: 'NJ', stateCode: 'NJ' },
  '557': { stateName: 'MO', stateCode: 'MO' },
  '559': { stateName: 'CA', stateCode: 'CA' },
  '561': { stateName: 'FL', stateCode: 'FL' },
  '562': { stateName: 'CA', stateCode: 'CA' },
  '563': { stateName: 'IA', stateCode: 'IA' },
  '564': { stateName: 'WA', stateCode: 'WA' },
  '567': { stateName: 'OH', stateCode: 'OH' },
  '570': { stateName: 'PA', stateCode: 'PA' },
  '571': { stateName: 'VA', stateCode: 'VA' },
  '572': { stateName: 'OK', stateCode: 'OK' },
  '573': { stateName: 'MO', stateCode: 'MO' },
  '574': { stateName: 'IN', stateCode: 'IN' },
  '575': { stateName: 'NM', stateCode: 'NM' },
  '579': { stateName: 'QUEBEC', stateCode: 'QUEBEC' },
  '580': { stateName: 'OK', stateCode: 'OK' },
  '581': { stateName: 'QUEBEC', stateCode: 'QUEBEC' },
  '582': { stateName: 'PA', stateCode: 'PA' },
  '584': { stateName: 'MANITOBA', stateCode: 'MANITOBA' },
  '585': { stateName: 'NY', stateCode: 'NY' },
  '586': { stateName: 'MI', stateCode: 'MI' },
  '587': { stateName: 'ALBERTA', stateCode: 'ALBERTA' },
  '601': { stateName: 'MS', stateCode: 'MS' },
  '602': { stateName: 'AZ', stateCode: 'AZ' },
  '603': { stateName: 'NH', stateCode: 'NH' },
  '604': { stateName: 'BRITISH COLUMBIA', stateCode: 'BRITISH COLUMBIA' },
  '605': { stateName: 'SD', stateCode: 'SD' },
  '606': { stateName: 'KY', stateCode: 'KY' },
  '607': { stateName: 'NY', stateCode: 'NY' },
  '608': { stateName: 'WI', stateCode: 'WI' },
  '609': { stateName: 'NJ', stateCode: 'NJ' },
  '610': { stateName: 'PA', stateCode: 'PA' },
  '612': { stateName: 'MN', stateCode: 'MN' },
  '613': { stateName: 'ONTARIO', stateCode: 'ONTARIO' },
  '614': { stateName: 'OH', stateCode: 'OH' },
  '615': { stateName: 'TN', stateCode: 'TN' },
  '616': { stateName: 'MI', stateCode: 'MI' },
  '617': { stateName: 'MA', stateCode: 'MA' },
  '618': { stateName: 'IL', stateCode: 'IL' },
  '619': { stateName: 'CA', stateCode: 'CA' },
  '620': { stateName: 'KS', stateCode: 'KS' },
  '623': { stateName: 'AZ', stateCode: 'AZ' },
  '624': { stateName: 'NY', stateCode: 'NY' },
  '626': { stateName: 'CA', stateCode: 'CA' },
  '628': { stateName: 'CA', stateCode: 'CA' },
  '629': { stateName: 'TN', stateCode: 'TN' },
  '630': { stateName: 'IL', stateCode: 'IL' },
  '631': { stateName: 'NY', stateCode: 'NY' },
  '636': { stateName: 'MO', stateCode: 'MO' },
  '639': { stateName: 'SASKATCHEWAN', stateCode: 'SASKATCHEWAN' },
  '640': { stateName: 'NJ', stateCode: 'NJ' },
  '641': { stateName: 'IA', stateCode: 'IA' },
  '645': { stateName: 'FL', stateCode: 'FL' },
  '646': { stateName: 'NY', stateCode: 'NY' },
  '647': { stateName: 'ONTARIO', stateCode: 'ONTARIO' },
  '649': {
    stateName: 'TURKS & CAICOS ISLANDS',
    stateCode: 'TURKS & CAICOS ISLANDS',
  },
  '650': { stateName: 'CA', stateCode: 'CA' },
  '651': { stateName: 'MN', stateCode: 'MN' },
  '656': { stateName: 'FL', stateCode: 'FL' },
  '657': { stateName: 'CA', stateCode: 'CA' },
  '658': { stateName: 'JAMAICA', stateCode: 'JAMAICA' },
  '659': { stateName: 'AL', stateCode: 'AL' },
  '660': { stateName: 'MO', stateCode: 'MO' },
  '661': { stateName: 'CA', stateCode: 'CA' },
  '662': { stateName: 'MS', stateCode: 'MS' },
  '664': { stateName: 'MONTSERRAT', stateCode: 'MONTSERRAT' },
  '667': { stateName: 'MD', stateCode: 'MD' },
  '669': { stateName: 'CA', stateCode: 'CA' },
  '670': { stateName: 'CNMI', stateCode: 'CNMI' },
  '671': { stateName: 'GU', stateCode: 'GU' },
  '672': { stateName: 'BRITISH COLUMBIA', stateCode: 'BRITISH COLUMBIA' },
  '678': { stateName: 'GA', stateCode: 'GA' },
  '680': { stateName: 'NY', stateCode: 'NY' },
  '681': { stateName: 'WV', stateCode: 'WV' },
  '682': { stateName: 'TX', stateCode: 'TX' },
  '683': { stateName: 'ONTARIO', stateCode: 'ONTARIO' },
  '684': { stateName: 'AS', stateCode: 'AS' },
  '686': { stateName: 'VA', stateCode: 'VA' },
  '689': { stateName: 'FL', stateCode: 'FL' },
  '701': { stateName: 'ND', stateCode: 'ND' },
  '702': { stateName: 'NV', stateCode: 'NV' },
  '703': { stateName: 'VA', stateCode: 'VA' },
  '704': { stateName: 'NC', stateCode: 'NC' },
  '705': { stateName: 'ONTARIO', stateCode: 'ONTARIO' },
  '706': { stateName: 'GA', stateCode: 'GA' },
  '707': { stateName: 'CA', stateCode: 'CA' },
  '708': { stateName: 'IL', stateCode: 'IL' },
  '709': {
    stateName: 'NEWFOUNDLAND AND LABRADOR',
    stateCode: 'NEWFOUNDLAND AND LABRADOR',
  },
  '712': { stateName: 'IA', stateCode: 'IA' },
  '713': { stateName: 'TX', stateCode: 'TX' },
  '714': { stateName: 'CA', stateCode: 'CA' },
  '715': { stateName: 'WI', stateCode: 'WI' },
  '716': { stateName: 'NY', stateCode: 'NY' },
  '717': { stateName: 'PA', stateCode: 'PA' },
  '718': { stateName: 'NY', stateCode: 'NY' },
  '719': { stateName: 'CO', stateCode: 'CO' },
  '720': { stateName: 'CO', stateCode: 'CO' },
  '721': { stateName: 'SINT MAARTEN', stateCode: 'SINT MAARTEN' },
  '724': { stateName: 'PA', stateCode: 'PA' },
  '725': { stateName: 'NV', stateCode: 'NV' },
  '726': { stateName: 'TX', stateCode: 'TX' },
  '727': { stateName: 'FL', stateCode: 'FL' },
  '728': { stateName: 'FL', stateCode: 'FL' },
  '730': { stateName: 'IL', stateCode: 'IL' },
  '731': { stateName: 'TN', stateCode: 'TN' },
  '732': { stateName: 'NJ', stateCode: 'NJ' },
  '734': { stateName: 'MI', stateCode: 'MI' },
  '737': { stateName: 'TX', stateCode: 'TX' },
  '738': { stateName: 'CA', stateCode: 'CA' },
  '740': { stateName: 'OH', stateCode: 'OH' },
  '742': { stateName: 'ONTARIO', stateCode: 'ONTARIO' },
  '743': { stateName: 'NC', stateCode: 'NC' },
  '747': { stateName: 'CA', stateCode: 'CA' },
  '753': { stateName: 'ONTARIO', stateCode: 'ONTARIO' },
  '754': { stateName: 'FL', stateCode: 'FL' },
  '757': { stateName: 'VA', stateCode: 'VA' },
  '758': { stateName: 'ST. LUCIA', stateCode: 'ST. LUCIA' },
  '760': { stateName: 'CA', stateCode: 'CA' },
  '762': { stateName: 'GA', stateCode: 'GA' },
  '763': { stateName: 'MN', stateCode: 'MN' },
  '765': { stateName: 'IN', stateCode: 'IN' },
  '767': { stateName: 'DOMINICA', stateCode: 'DOMINICA' },
  '769': { stateName: 'MS', stateCode: 'MS' },
  '770': { stateName: 'GA', stateCode: 'GA' },
  '771': { stateName: 'DC', stateCode: 'DC' },
  '772': { stateName: 'FL', stateCode: 'FL' },
  '773': { stateName: 'IL', stateCode: 'IL' },
  '774': { stateName: 'MA', stateCode: 'MA' },
  '775': { stateName: 'NV', stateCode: 'NV' },
  '778': { stateName: 'BRITISH COLUMBIA', stateCode: 'BRITISH COLUMBIA' },
  '779': { stateName: 'IL', stateCode: 'IL' },
  '780': { stateName: 'ALBERTA', stateCode: 'ALBERTA' },
  '781': { stateName: 'MA', stateCode: 'MA' },
  '782': {
    stateName: 'NOVA SCOTIA - PRINCE EDWARD ISLAND',
    stateCode: 'NOVA SCOTIA - PRINCE EDWARD ISLAND',
  },
  '784': {
    stateName: 'ST. VINCENT & GRENADINES',
    stateCode: 'ST. VINCENT & GRENADINES',
  },
  '785': { stateName: 'KS', stateCode: 'KS' },
  '786': { stateName: 'FL', stateCode: 'FL' },
  '787': { stateName: 'PR', stateCode: 'PR' },
  '801': { stateName: 'UT', stateCode: 'UT' },
  '802': { stateName: 'VT', stateCode: 'VT' },
  '803': { stateName: 'SC', stateCode: 'SC' },
  '804': { stateName: 'VA', stateCode: 'VA' },
  '805': { stateName: 'CA', stateCode: 'CA' },
  '806': { stateName: 'TX', stateCode: 'TX' },
  '807': { stateName: 'ONTARIO', stateCode: 'ONTARIO' },
  '808': { stateName: 'HI', stateCode: 'HI' },
  '809': { stateName: 'DOMINICAN REPUBLIC', stateCode: 'DOMINICAN REPUBLIC' },
  '810': { stateName: 'MI', stateCode: 'MI' },
  '812': { stateName: 'IN', stateCode: 'IN' },
  '813': { stateName: 'FL', stateCode: 'FL' },
  '814': { stateName: 'PA', stateCode: 'PA' },
  '815': { stateName: 'IL', stateCode: 'IL' },
  '816': { stateName: 'MO', stateCode: 'MO' },
  '817': { stateName: 'TX', stateCode: 'TX' },
  '818': { stateName: 'CA', stateCode: 'CA' },
  '819': { stateName: 'QUEBEC', stateCode: 'QUEBEC' },
  '820': { stateName: 'CA', stateCode: 'CA' },
  '821': { stateName: 'SC', stateCode: 'SC' },
  '825': { stateName: 'ALBERTA', stateCode: 'ALBERTA' },
  '826': { stateName: 'VA', stateCode: 'VA' },
  '828': { stateName: 'NC', stateCode: 'NC' },
  '829': { stateName: 'DOMINICAN REPUBLIC', stateCode: 'DOMINICAN REPUBLIC' },
  '830': { stateName: 'TX', stateCode: 'TX' },
  '831': { stateName: 'CA', stateCode: 'CA' },
  '832': { stateName: 'TX', stateCode: 'TX' },
  '835': { stateName: 'PA', stateCode: 'PA' },
  '838': { stateName: 'NY', stateCode: 'NY' },
  '839': { stateName: 'SC', stateCode: 'SC' },
  '840': { stateName: 'CA', stateCode: 'CA' },
  '843': { stateName: 'SC', stateCode: 'SC' },
  '845': { stateName: 'NY', stateCode: 'NY' },
  '847': { stateName: 'IL', stateCode: 'IL' },
  '848': { stateName: 'NJ', stateCode: 'NJ' },
  '849': { stateName: 'DOMINICAN REPUBLIC', stateCode: 'DOMINICAN REPUBLIC' },
  '850': { stateName: 'FL', stateCode: 'FL' },
  '854': { stateName: 'SC', stateCode: 'SC' },
  '856': { stateName: 'NJ', stateCode: 'NJ' },
  '857': { stateName: 'MA', stateCode: 'MA' },
  '858': { stateName: 'CA', stateCode: 'CA' },
  '859': { stateName: 'KY', stateCode: 'KY' },
  '860': { stateName: 'CT', stateCode: 'CT' },
  '861': { stateName: 'IL', stateCode: 'IL' },
  '862': { stateName: 'NJ', stateCode: 'NJ' },
  '863': { stateName: 'FL', stateCode: 'FL' },
  '864': { stateName: 'SC', stateCode: 'SC' },
  '865': { stateName: 'TN', stateCode: 'TN' },
  '867': {
    stateName: 'NORTHWEST TERRITORIES -YUKON - NUNAVUT',
    stateCode: 'NORTHWEST TERRITORIES -YUKON - NUNAVUT',
  },
  '868': { stateName: 'TRINIDAD & TOBAGO', stateCode: 'TRINIDAD & TOBAGO' },
  '869': { stateName: 'ST. KITTS & NEVIS', stateCode: 'ST. KITTS & NEVIS' },
  '870': { stateName: 'AR', stateCode: 'AR' },
  '872': { stateName: 'IL', stateCode: 'IL' },
  '873': { stateName: 'QUEBEC', stateCode: 'QUEBEC' },
  '876': { stateName: 'JAMAICA', stateCode: 'JAMAICA' },
  '878': { stateName: 'PA', stateCode: 'PA' },
  '879': {
    stateName: 'NEWFOUNDLAND AND LABRADOR',
    stateCode: 'NEWFOUNDLAND AND LABRADOR',
  },
  '901': { stateName: 'TN', stateCode: 'TN' },
  '902': {
    stateName: 'NOVA SCOTIA - PRINCE EDWARD ISLAND',
    stateCode: 'NOVA SCOTIA - PRINCE EDWARD ISLAND',
  },
  '903': { stateName: 'TX', stateCode: 'TX' },
  '904': { stateName: 'FL', stateCode: 'FL' },
  '905': { stateName: 'ONTARIO', stateCode: 'ONTARIO' },
  '906': { stateName: 'MI', stateCode: 'MI' },
  '907': { stateName: 'AK', stateCode: 'AK' },
  '908': { stateName: 'NJ', stateCode: 'NJ' },
  '909': { stateName: 'CA', stateCode: 'CA' },
  '910': { stateName: 'NC', stateCode: 'NC' },
  '912': { stateName: 'GA', stateCode: 'GA' },
  '913': { stateName: 'KS', stateCode: 'KS' },
  '914': { stateName: 'NY', stateCode: 'NY' },
  '915': { stateName: 'TX', stateCode: 'TX' },
  '916': { stateName: 'CA', stateCode: 'CA' },
  '917': { stateName: 'NY', stateCode: 'NY' },
  '918': { stateName: 'OK', stateCode: 'OK' },
  '919': { stateName: 'NC', stateCode: 'NC' },
  '920': { stateName: 'WI', stateCode: 'WI' },
  '924': { stateName: 'MN', stateCode: 'MN' },
  '925': { stateName: 'CA', stateCode: 'CA' },
  '928': { stateName: 'AZ', stateCode: 'AZ' },
  '929': { stateName: 'NY', stateCode: 'NY' },
  '930': { stateName: 'IN', stateCode: 'IN' },
  '931': { stateName: 'TN', stateCode: 'TN' },
  '934': { stateName: 'NY', stateCode: 'NY' },
  '936': { stateName: 'TX', stateCode: 'TX' },
  '937': { stateName: 'OH', stateCode: 'OH' },
  '938': { stateName: 'AL', stateCode: 'AL' },
  '939': { stateName: 'PR', stateCode: 'PR' },
  '940': { stateName: 'TX', stateCode: 'TX' },
  '941': { stateName: 'FL', stateCode: 'FL' },
  '943': { stateName: 'GA', stateCode: 'GA' },
  '945': { stateName: 'TX', stateCode: 'TX' },
  '947': { stateName: 'MI', stateCode: 'MI' },
  '948': { stateName: 'VA', stateCode: 'VA' },
  '949': { stateName: 'CA', stateCode: 'CA' },
  '951': { stateName: 'CA', stateCode: 'CA' },
  '952': { stateName: 'MN', stateCode: 'MN' },
  '954': { stateName: 'FL', stateCode: 'FL' },
  '956': { stateName: 'TX', stateCode: 'TX' },
  '959': { stateName: 'CT', stateCode: 'CT' },
  '970': { stateName: 'CO', stateCode: 'CO' },
  '971': { stateName: 'OR', stateCode: 'OR' },
  '972': { stateName: 'TX', stateCode: 'TX' },
  '973': { stateName: 'NJ', stateCode: 'NJ' },
  '975': { stateName: 'MO', stateCode: 'MO' },
  '978': { stateName: 'MA', stateCode: 'MA' },
  '979': { stateName: 'TX', stateCode: 'TX' },
  '980': { stateName: 'NC', stateCode: 'NC' },
  '983': { stateName: 'CO', stateCode: 'CO' },
  '984': { stateName: 'NC', stateCode: 'NC' },
  '985': { stateName: 'LA', stateCode: 'LA' },
  '986': { stateName: 'ID', stateCode: 'ID' },
  '989': { stateName: 'MI', stateCode: 'MI' },
};
